server:
  port: 8081

spring:
  application:
    name: alert-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: alert-service
          uri: lb://alerts-api
          predicates:
            - Path=/api/v1/**
          filters:
            - JwtTokenFilter
            - StripPrefix=0
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        namespace: alerts-demo
        primary-port-name: http
      health:
        enabled: false

clerk:
  jwks-url: https://ruling-wolf-12.clerk.accounts.dev/.well-known/jwks.json 