name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.9.6

    - name: Set Docker tag
      id: version
      run: |
        VERSION="v$(date +%s)"
        echo "TAG=$VERSION" >> $GITHUB_ENV
        echo "Image tag will be: $VERSION"

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build image with Spring Boot
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/alert-gateway:${{ env.TAG }}

    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/alert-gateway:${{ env.TAG }} 