name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.6

      - name: Set Docker tag (timestamp)
        id: tag
        run: |
          TAG=v$(date +%s)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Image tag will be: $TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image using Spring Boot
        run: ./mvnw -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/alert-gateway:${{ env.TAG }} spring-boot:build-image
  
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/alert-gateway:${{ env.TAG }}